# Generated by Django 4.0.6 on 2022-09-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=100)),
                ('education', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('bio', models.TextField()),
            ],
        ),
    ]
