# Generated by Django 4.0.6 on 2022-09-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
                ('subjects', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='course',
            field=models.CharField(default='pcmb', max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], default='Male', max_length=100),
        ),
    ]
