# Generated by Django 4.0.6 on 2022-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_staff_course_alter_staff_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='course',
            field=models.CharField(default='pcm', max_length=100),
        ),
    ]
