# Generated by Django 4.0.6 on 2022-10-01 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_staff_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('batch', models.CharField(max_length=300)),
                ('marks', models.IntegerField()),
                ('course', models.ForeignKey(default='pcmb', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='toppers', to='main.course')),
            ],
        ),
    ]
