# Generated by Django 4.0.6 on 2022-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='replied',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], default='No', max_length=100),
        ),
    ]
